"""
O'zbekiston Respublikasining 14 ta viloyati va tumanlari ro'yxati (Open Budget standartlari bo'yicha).
"""

REGIONS = [
    {"id": 1, "name": "Toshkent shahri", "short_name": "Toshkent sh."},
    {"id": 2, "name": "Toshkent viloyati", "short_name": "Toshkent vil."},
    {"id": 3, "name": "Andijon viloyati", "short_name": "Andijon"},
    {"id": 4, "name": "Buxoro viloyati", "short_name": "Buxoro"},
    {"id": 5, "name": "Farg'ona viloyati", "short_name": "Farg'ona"},
    {"id": 6, "name": "Jizzax viloyati", "short_name": "Jizzax"},
    {"id": 7, "name": "Xorazm viloyati", "short_name": "Xorazm"},
    {"id": 8, "name": "Namangan viloyati", "short_name": "Namangan"},
    {"id": 9, "name": "Navoiy viloyati", "short_name": "Navoiy"},
    {"id": 10, "name": "Qashqadaryo viloyati", "short_name": "Qashqadaryo"},
    {"id": 11, "name": "Qoraqalpog'iston Respublikasi", "short_name": "Qoraqalpog'iston"},
    {"id": 12, "name": "Samarqand viloyati", "short_name": "Samarqand"},
    {"id": 13, "name": "Sirdaryo viloyati", "short_name": "Sirdaryo"},
    {"id": 14, "name": "Surxondaryo viloyati", "short_name": "Surxondaryo"},
]

DISTRICTS = {
    1: [
        {"id": 101, "name": "Yunusobod tumani"},
        {"id": 102, "name": "Mirzo Ulug'bek tumani"},
        {"id": 103, "name": "Chilonzor tumani"},
        {"id": 104, "name": "Shayxontohur tumani"},
        {"id": 105, "name": "Olmazor tumani"},
        {"id": 106, "name": "Yashnobod tumani"},
        {"id": 107, "name": "Mirobod tumani"},
        {"id": 108, "name": "Yakkasaroy tumani"},
        {"id": 109, "name": "Uchtepa tumani"},
        {"id": 110, "name": "Sergeli tumani"},
        {"id": 111, "name": "Bektemir tumani"},
        {"id": 112, "name": "Yangihayot tumani"},
    ],
    2: [
        {"id": 201, "name": "Zangiota tumani"},
        {"id": 202, "name": "Qibray tumani"},
        {"id": 203, "name": "Toshkent tumani"},
        {"id": 204, "name": "Chirchiq shahri"},
        {"id": 205, "name": "Olmaliq shahri"},
        {"id": 206, "name": "Angren shahri"},
        {"id": 207, "name": "Yangiyo'l tumani"},
        {"id": 208, "name": "Bo'stonliq tumani"},
        {"id": 209, "name": "Parkent tumani"},
        {"id": 210, "name": "O'rtachirchiq tumani"},
        {"id": 211, "name": "Yuqorichirchiq tumani"},
        {"id": 212, "name": "Quyichirchiq tumani"},
    ],
    3: [
        {"id": 301, "name": "Andijon shahri"},
        {"id": 302, "name": "Andijon tumani"},
        {"id": 303, "name": "Asaka tumani"},
        {"id": 304, "name": "Shahrixon tumani"},
        {"id": 305, "name": "Xo'jaobod tumani"},
        {"id": 306, "name": "Oltinko'l tumani"},
        {"id": 307, "name": "Baliqchi tumani"},
        {"id": 308, "name": "Paxtaobod tumani"},
        {"id": 309, "name": "Qo'rg'ontepa tumani"},
        {"id": 310, "name": "Izboskan tumani"},
    ],
    4: [
        {"id": 401, "name": "Buxoro shahri"},
        {"id": 402, "name": "Buxoro tumani"},
        {"id": 403, "name": "G'ijduvon tumani"},
        {"id": 404, "name": "Kogon shahri"},
        {"id": 405, "name": "Vobkent tumani"},
        {"id": 406, "name": "Jondor tumani"},
        {"id": 407, "name": "Romitan tumani"},
        {"id": 408, "name": "Peshku tumani"},
        {"id": 409, "name": "Shofirkon tumani"},
    ],
    5: [
        {"id": 501, "name": "Farg'ona shahri"},
        {"id": 502, "name": "Qo'qon shahri"},
        {"id": 503, "name": "Marg'ilon shahri"},
        {"id": 504, "name": "Farg'ona tumani"},
        {"id": 505, "name": "Oltiariq tumani"},
        {"id": 506, "name": "Rishton tumani"},
        {"id": 507, "name": "Bag'dod tumani"},
        {"id": 508, "name": "Beshariq tumani"},
        {"id": 509, "name": "Uchko'prik tumani"},
        {"id": 510, "name": "Quva tumani"},
    ],
    6: [
        {"id": 601, "name": "Jizzax shahri"},
        {"id": 602, "name": "Zomin tumani"},
        {"id": 603, "name": "Sharof Rashidov tumani"},
        {"id": 604, "name": "G'allaorol tumani"},
        {"id": 605, "name": "Baxmal tumani"},
        {"id": 606, "name": "Do'stlik tumani"},
        {"id": 607, "name": "Zarbdor tumani"},
    ],
    7: [
        {"id": 701, "name": "Urganch shahri"},
        {"id": 702, "name": "Xiva shahri"},
        {"id": 703, "name": "Urganch tumani"},
        {"id": 704, "name": "Xiva tumani"},
        {"id": 705, "name": "Xonqa tumani"},
        {"id": 706, "name": "Hazorasp tumani"},
        {"id": 707, "name": "Gurlan tumani"},
        {"id": 708, "name": "Shovot tumani"},
    ],
    8: [
        {"id": 801, "name": "Namangan shahri"},
        {"id": 802, "name": "Namangan tumani"},
        {"id": 803, "name": "Chust tumani"},
        {"id": 804, "name": "Pop tumani"},
        {"id": 805, "name": "Kosonsoy tumani"},
        {"id": 806, "name": "Uychi tumani"},
        {"id": 807, "name": "To'raqo'rg'on tumani"},
        {"id": 808, "name": "Yangiqo'rg'on tumani"},
    ],
    9: [
        {"id": 901, "name": "Navoiy shahri"},
        {"id": 902, "name": "Zarafshon shahri"},
        {"id": 903, "name": "Karmana tumani"},
        {"id": 904, "name": "Qiziltepa tumani"},
        {"id": 905, "name": "Xatirchi tumani"},
        {"id": 906, "name": "Nurota tumani"},
        {"id": 907, "name": "Uchquduq tumani"},
    ],
    10: [
        {"id": 1001, "name": "Qarshi shahri"},
        {"id": 1002, "name": "Shahrisabz shahri"},
        {"id": 1003, "name": "Qarshi tumani"},
        {"id": 1004, "name": "Shahrisabz tumani"},
        {"id": 1005, "name": "Kitob tumani"},
        {"id": 1006, "name": "Koson tumani"},
        {"id": 1007, "name": "G'uzor tumani"},
        {"id": 1008, "name": "Yakkabog' tumani"},
        {"id": 1009, "name": "Nishon tumani"},
    ],
    11: [
        {"id": 1101, "name": "Nukus shahri"},
        {"id": 1102, "name": "Nukus tumani"},
        {"id": 1103, "name": "Beruniy tumani"},
        {"id": 1104, "name": "To'rtko'l tumani"},
        {"id": 1105, "name": "Xo'jayli tumani"},
        {"id": 1106, "name": "Amudaryo tumani"},
        {"id": 1107, "name": "Chimboy tumani"},
        {"id": 1108, "name": "Qo'ng'irot tumani"},
    ],
    12: [
        {"id": 1201, "name": "Samarqand shahri"},
        {"id": 1202, "name": "Samarqand tumani"},
        {"id": 1203, "name": "Urgut tumani"},
        {"id": 1204, "name": "Pastdarg'om tumani"},
        {"id": 1205, "name": "Kattaqo'rg'on shahri"},
        {"id": 1206, "name": "Kattaqo'rg'on tumani"},
        {"id": 1207, "name": "Payariq tumani"},
        {"id": 1208, "name": "Bulung'ur tumani"},
        {"id": 1209, "name": "Jomboy tumani"},
        {"id": 1210, "name": "Oqdaryo tumani"},
    ],
    13: [
        {"id": 1301, "name": "Guliston shahri"},
        {"id": 1302, "name": "Shirin shahri"},
        {"id": 1303, "name": "Yangiyer shahri"},
        {"id": 1304, "name": "Guliston tumani"},
        {"id": 1305, "name": "Sirdaryo tumani"},
        {"id": 1306, "name": "Boyovut tumani"},
        {"id": 1307, "name": "Sayxunobod tumani"},
        {"id": 1308, "name": "Mirzaobod tumani"},
    ],
    14: [
        {"id": 1401, "name": "Termiz shahri"},
        {"id": 1402, "name": "Termiz tumani"},
        {"id": 1403, "name": "Denov tumani"},
        {"id": 1404, "name": "Sherobod tumani"},
        {"id": 1405, "name": "Sho'rchi tumani"},
        {"id": 1406, "name": "Boysun tumani"},
        {"id": 1407, "name": "Qumqo'rg'on tumani"},
        {"id": 1408, "name": "Sariosiyo tumani"},
        {"id": 1409, "name": "Muzrabot tumani"},
    ],
}

def get_region_name(region_id: int) -> str:
    for reg in REGIONS:
        if reg["id"] == region_id:
            return reg["name"]
    return "Noma'lum viloyat"

def get_district_name(region_id: int, district_id: int) -> str:
    districts = DISTRICTS.get(region_id, [])
    for d in districts:
        if d["id"] == district_id:
            return d["name"]
    return "Noma'lum tuman"
